// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoryyBo1CuzicxucvETifJIWjHXfGs6iU',
    appId: '1:880361340287:web:bf3eb3c29447f3bd04ee4a',
    messagingSenderId: '880361340287',
    projectId: 'student-expense-db',
    authDomain: 'student-expense-db.firebaseapp.com',
    storageBucket: 'student-expense-db.firebasestorage.app',
    measurementId: 'G-3TXM786GG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWnnncaksSnqsiPpX3112RdZAQJWABME',
    appId: '1:880361340287:android:9c58607a7b555a1b04ee4a',
    messagingSenderId: '880361340287',
    projectId: 'student-expense-db',
    storageBucket: 'student-expense-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoryyBo1CuzicxucvETifJIWjHXfGs6iU',
    appId: '1:880361340287:web:d1c6ec6b1a05f24804ee4a',
    messagingSenderId: '880361340287',
    projectId: 'student-expense-db',
    authDomain: 'student-expense-db.firebaseapp.com',
    storageBucket: 'student-expense-db.firebasestorage.app',
    measurementId: 'G-NWTW4D90RX',
  );

}